client source code refactorization

diff --git a/server/bin/natfree-update-server-arithmetic b/server/bin/natfree-update-server-arithmetic
--- a/server/bin/natfree-update-server-arithmetic
+++ b/server/bin/natfree-update-server-arithmetic
@@ -4,14 +4,11 @@
 # global vars #
 ###############
 
-# Asume server uses 5th available IP in subnet
-SRV_IP_NUMBER=5
-
 # get default route iface
 GW_IFACE="$(get_gw_iface)"
 
 # load common functions
-. /usr/share/update-hosts/update-hosts-common
+. /usr/share/natfree-common/natfree-common
 
 # name of virtual iface to assign when
 # GW_IFACE brings up
@@ -55,15 +52,15 @@ main(){
 				usage
 				;;
 		esac
+
+		# validate
+		echo "$SRV_IP_NUMBER" |grep -q "^[[:digit:]]\+$" || die "Invalid IP number/position $SRV_IP_NUMBER"
+		[ "$SRV_VIRTUAL_IFACE" ] || die "Undefined virtual interface"
+
+		[ "$GW_IFACE" ] || die "Undefined physical interface"
+		get_interface_list | grep -qFX "$GW_IFACE" || die "Invalid physical interface $GW_IFACE"
 		shift
 	done
-
-	echo "$SRV_IP_NUMBER" |grep -q "^[[:digit:]]\+$" || die "Invalid IP number/position $SRV_IP_NUMBER"
-
-	[ "$SRV_VIRTUAL_IFACE" ] || die "Undefined virtual interface"
-
-	[ "$GW_IFACE" ] || die "Undefined physical interface"
-	get_interface_list | grep -qFX "$GW_IFACE" || die "Invalid physical interface $GW_IFACE"
 
 	# recopile necessary data
 
@@ -91,15 +88,14 @@ main(){
 	SRV_IP="${SRV_CIDR%/*}"
 
 	# update server n4d variables
-	# TODO: avoid this dirty trick ...
+	# TODO: please avoid this dirty trick ...
 	# BEGIN 
 	#N4DVARS_DIR="/var/lib/n4d/variables"
-	N4DVARS_FILES="SRV_IP:$SRV_IP CLIENT_LDAP_URI: CLIENT_LDAP_URI_NOSSL:"
-	N4DVARS_FILES="SRV_IP:$SRV_IP"
+	N4DVARS_FILES="SRV_IP,$SRV_IP CLIENT_LDAP_URI,ldaps://$SRV_IP CLIENT_LDAP_URI_NOSSL,ldap://$SRV_IP"
 	for f in "$N4DVARS_FILES" ; do
-		F="${N4DVARS_DIR}/${f:*}"
-		STR="\"value\":"
-		sed -i -n "/\"value\":/s%:.*$%: $SRV_IP,%"
+		VAR_FILE="${N4DVARS_DIR}/${f%,*}"
+		VAR_VALUE="${f#*,}"
+		sed -i -n "/\"value\":/s%:.*$%: \"$VAR_VALUE\",%" "$VAR_FILE"
 	done
 	service n4d restart
 	# END
diff --git a/server/usr/share/natfree-server/natfree-server-arithmetic b/server/usr/share/natfree-server/natfree-server-arithmetic
--- a/server/usr/share/natfree-server/natfree-server-arithmetic
+++ b/server/usr/share/natfree-server/natfree-server-arithmetic
@@ -1,81 +1,25 @@
 #!/bin/sh
 
-###############
-# global vars #
-###############
-
-# Asume server uses 5th available IP in subnet
-SRV_IP_NUMBER=5
+#####################
+#  vars & functions #
+#####################
 
 # get default route iface
 GW_IFACE="$(get_gw_iface)"
 
 # load common functions
-. /usr/share/update-hosts/update-hosts-common
+. /usr/share/natfree-common/natfree-common
 
-# name of virtual iface to assign when
-# GW_IFACE brings up
-SRV_VIRTUAL_IFACE="natfree00"
+########
+# main #
+########
 
+[ "$GW_IFACE" ] || die "Unable to find network gateway iface"
+[ "$IFACE" ] || die "Undefined 'IFACE' environment var. May be not running under networkd-dispatcher?"
 
-#############
-# functions #
-#############
-main(){
-	# main
-	######
-	# check environment
-	[ "$SRV_VIRTUAL_IFACE" ] || die "Undefined SRV_VIRTUAL_IFACE variable"
-	[ "$GW_IFACE" ] || die "Unable to find network gateway iface"
-	[ "$IFACE" ] || die "Undefined 'IFACE' environment var. May be not running under networkd-dispatcher?"
+# correct interface up?
+[ "$GW_IFACE" = "$IFACE" ] || exit 0
 
-	# correct interface up?
-	[ "$GW_IFACE" = "$IFACE" ] || exit 0
-
-	# recopile necessary data
-
-	# get ip/mask in CIDR notation
-	CIDR="$(get_iface_cidr "$GW_IFACE")"
-	[ "$CIDR" ] || die "Unable to retrieve IP address from $GW_IFACE"
-
-	# get SRV_IP_NUMBER available ip in subnet
-	SRV_CIDR="$(get_srv_cidr "$CIDR" "$SRV_IP_NUMBER")"
-
-	# check existence of SRV_VIRTUAL_IFACE and create it if needed
-	if ! get_interface_list | grep -qFX "$SRV_VIRTUAL_IFACE" ; then
-		create_virt_iface "$SRV_VIRTUAL_IFACE"
-		# test creation
-		get_interface_list | grep -qFX "$SRV_VIRTUAL_IFACE" || die "Unable to create virtual interface $SRV_VIRTUAL_IFACE"
-	fi
-
-	# assign SRV_IP to virtual interface
-	# TODO: test this code !!!!!!!
-	ip link set dev "$SRV_VIRTUAL_IFACE" down
-	ip addr add "$SRV_CIDR" dev "$SRV_VIRTUAL_IFACE"
-	ip link set dev "$SRV_VIRTUAL_IFACE" up
-
-	# extract SRV_IP
-	SRV_IP="${SRV_CIDR%/*}"
-
-	# update server n4d variables
-	# TODO: avoid this dirty trick ...
-	# BEGIN 
-	#N4DVARS_DIR="/var/lib/n4d/variables"
-	N4DVARS_FILES="SRV_IP:$SRV_IP CLIENT_LDAP_URI: CLIENT_LDAP_URI_NOSSL:"
-	N4DVARS_FILES="SRV_IP:$SRV_IP"
-	for f in "$N4DVARS_FILES" ; do
-		F="${N4DVARS_DIR}/${f:*}"
-		STR="\"value\":"
-		sed -i -n "/\"value\":/s%:.*$%: $SRV_IP,%"
-	done
-	service n4d restart
-	# END
-
-}
-
-################
-# main program #
-################
-main
+natfree-update-server-arithmetic -i "$GW_IFACE"
 exit 0
 
